modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Outlying-Destiny/Outlying-Core/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/Outlying-Destiny/Outlying-Core"
logoFile="Outlying-Core_logo.png"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.outlyingcore]] 
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.outlyingcore]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.outlyingcore]]
    modId="enderio"
    mandatory=true
    versionRange="${enderio_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.outlyingcore]]
    modId="ironjetpacks"
    mandatory=true
    versionRange="${ironjetpacks_version_range}"
    ordering="AFTER"
    side="BOTH"
