name: Bug Report
description: Create a report to help reproduce and fix the issue
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Before creating an issue report, make sure by using the search functionality that someone hasn't already made one.
        If you find an open issue about the same problem, please add to that discussion instead of making a new report.
        Please also make sure you are using the latest version of the mod and/or check if the issue exists on the latest release.
  - type: input
    id: outlyingcore-version
    attributes:
      label: Outlying Core version
      description: You can find the version of the mod by looking at the mods' file name or in-game by clicking on the mods' button in the main menu.
      placeholder: 1.0.0
    validations:
      required: true
  - type: input
    id: modpack
    attributes:
      label: Modpack & Version
      description: If you are running a Modpack, please provide the name and version of the pack.
      value: Outlying Destiny
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: Issue Summary
      description: Briefly explain your issue in a few plain sentences, e.g. "X has Y issue" "When I do X, Y happens instead of Z". You may copy and paste the issue title here if it is suitable.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.
      placeholder: |
        1. Open Mc...
        2. Do stuff...
        3. See error...
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Log files
      description: "Link(s) to any log files you can provide, typically /logs/debug.log and /logs/latest.log"
      placeholder: |
        https://pastebin.com/
        https://pste.ch/
        https://paste.feed-the-beast.com/
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Add any other context about the problem here
    validations:
      required: false
